review
emsiish/Skin-care-recs pull request #1
Opened 2024-01-30 09:37 UTC by emsiish

2024-02-02 17:36 UTC, Teddy15 requested changes

2024-02-02 17:36 UTC, Teddy15 commented on backend/.mvn/wrapper/maven-wrapper.properties
> +distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/3.9.5/apache-maven-3.9.5-bin.zip
Този файл не ти е нужен в хранилището, слагай такива файлове в git ignore.

2024-02-02 17:36 UTC, Teddy15 commented on backend/mvnw
> +#!/bin/sh
Този файл не ти е нужен в хранилището, слагай такива файлове в git ignore.

2024-02-02 17:36 UTC, Teddy15 commented on backend/mvnw.cmd
> +@REM ----------------------------------------------------------------------------
Този файл не ти е нужен в хранилището, слагай такива файлове в git ignore.

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/DoctorController.java
> +        return doctorService.addDoctor(doctor);
Един съвет - добави си логове, ще улеснят процеса на дебъгване. Логовете обаче нека имат някакви уместни и смислени съобщения а не просто "test1", "method addDoctor" или нещо подобно
Виж slf4j dependency-то и как се използва.

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/resources/DoctorRatingResource.java
> +package com.example.skincarerecs.controller.resources;
Както говорихме, преименувай си на DoctorRatingDto класа. Като това важи за всички resource класове, които имаш. Пакетът също го прекръсти на dto.
Друго важно нещо - помисли кои полета не трябва да са празни (ако има такива).
Разгледай @NotNull, @NotBlank, @NotEmpty анотациите. (javax.validation.constraints им е пакетът, виж кое dependency трябва да се добави, ако има нужда също) 
Също така, ако искаш някакви custom валидации да имаш за имейл/телефон/каквото и да е - възможно е.
Искам добре да помислиш тези твои Data transfer objects от какви задължителни полета  се нуждаят : )
Пиши ми, ако имаш нужда от помощ

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/resources/DoctorRatingResource.java
> +package com.example.skincarerecs.controller.resources;
Важи за всичките класове. Няма да копирам коментара.
Също, за да се валидират тези анотации накрая, в съответния контролер клас преди някой @RequestBody параметър трябва да добавиш @Valid анотацията (javax.validation)

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/entity/DoctorRating.java
> +    private int rating;
Тоест, мога да дам само 1 или 2 звезди, например, не мога да дам 1,5 като рейтинг на някого?

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/entity/ProductRating.java
> +    private int rating;
Тоест, мога да дам само 1 или 2 звезди, например, не мога да дам 1,5 като рейтинг на някого?

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/entity/User.java
> +    private String username;
Имейл няма ли да пазиш? Това е обвързано с аутентикацията ти всъщност. Трябва да прецениш имейл ли е по-добре или username. Кое какви функции има, как те лимитира, ако те лимитира и т.н.

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/mapper/DoctorMapper.java
> +    DoctorMapper DOCTOR_MAPPER = Mappers.getMapper(DoctorMapper.class);
Защо правиш извикване към това factory?

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/mapper/DoctorMapper.java
> +    DoctorMapper DOCTOR_MAPPER = Mappers.getMapper(DoctorMapper.class);
Същия въпрос се отнася към всички mapper-и

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/mapper/DoctorMapper.java
> +    DoctorMapper DOCTOR_MAPPER = Mappers.getMapper(DoctorMapper.class);
Оставям го тук, за да го видиш също: относно въпросът с мапърите, може да изредиш кои останали мапъри искаш да ползваш в DoctorMapper например.
Това става като напишеш @Mapper(uses = {TestMapper.class})
Другото, което е, виж какво е componentModal = "spring". Ето така се ползва: @Mapper(componentModel="spring").

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/repository/TagRepository.java
> +    List<Tag> findAllByNameIn(List<String> tagsNames);
Защо си кръстила този метод findAllByNameIn, а не просто findAllByName ?

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/DoctorRatingService.java
> +    List<DoctorRatingResource> getAllDoctorRatings(Long doctorId);
Не мисля, че някъде ще ти трябва да листваш всички дадени оценки на докторите от всички потребители? 
Поне не се сещам, ако бъркам, моля поправи ме

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/DoctorService.java
> +    DoctorResource updateDoctor(Long id, DoctorResource doctor);
Помисли дали същото DTO трябва да ползваш при update. Тоест, помисли кои данни трябва да се ъпдейтват и кои не

2024-02-02 17:36 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/ProductRatingService.java
> +    ProductRatingResource updateProductRating(Long productId, Long id, ProductRatingResource productRating);
Кой и кога редактира оценките на продуктите?

2024-02-03 19:12 UTC, emsiish commented on backend/src/main/java/com/example/skincarerecs/service/DoctorRatingService.java
> +    List<DoctorRatingResource> getAllDoctorRatings(Long doctorId);
Ами мислих, че ще е хубаво примерно като цъкнеш някой доктор и да се display-ват оценките и коментарите дадени за него

2024-02-05 17:05 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/repository/TagRepository.java
> +    List<Tag> findAllByNameIn(List<String> tagsNames);
Ненужен въпрос, на второ четене разбрах защо. findAllByNameIn не е достатъчно описателно според мен, ако за пръв път четеш кода може да те обърка
findAllByNameInList или нещо такова е по-добре според мен

2024-02-05 17:06 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/DoctorRatingService.java
> +    List<DoctorRatingResource> getAllDoctorRatings(Long doctorId);
Ясно, разбрах, ок

2024-02-05 17:25 UTC, Teddy15 requested changes

2024-02-05 17:25 UTC, Teddy15 commented on backend/pom.xml
> +			<groupId>org.flywaydb</groupId>
Добавила си dependency-то, но не виждам миграции за базата ти
Ще е хубаво да добавиш няколко миграции за създаването на таблциите
Ако имаш нужда от помощ, пиши ми на лично, за да ги видим

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/CorsConfig.java
> +    public void addCorsMappings(CorsRegistry registry) {
Само вметка, че евентуално, когато настроиш аутентикацията и ауторизацията на приложнеието ти, този конфиг и логиката за него най-вероятно ще трябва да се премести. Когато си готова да го направиш, ако имаш затруднения, пиши ми, но исках да си наясно

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/DoctorController.java
> +        return doctorService.addDoctor(doctor);
Важи за всеки контролер + сървис клас

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/resources/UserResource.java
> +    private List<String> tags_names;
Придържай се имената на методите и променливите ти да следват camelCase конвенцията
Тоест, tags_names -> tagNames

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/resources/ProductResource.java
> +    private List<String> tags_names;
Придържай се имената на методите и променливите ти да следват camelCase конвенцията
Тоест, tags_names -> tagNames

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/resources/ProductRatingResource.java
> +    private String product_name;
Придържай се имената на методите и променливите ти да следват camelCase конвенцията
Тоест, product_name -> productName

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/controller/resources/DoctorResource.java
> +    private String telephone;
Може би по-добре phoneNumber да се казва полето

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/entity/Doctor.java
> +    private String telephone;
тук също phoneNumber

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/TagService.java
> +    TagResource updateTag(Long id, TagResource tag);
Кой и кога ъпдейтва таговете? Ако за момента таговете ще можеш само ръчно да ги вкарваш, колко точно от изписаната функционалност ти трябва?
Евентуално аз си представям, че някой с роля Админ би трябвало да редактира такава информация и да има такива права. Остави си функционалността, но не мисля, че ти е нужна в момента при положение, че не ти е описано нищо за Админ панел в Заданието на ДР. Мисълта ми е да не губиш време с излишни за момента добавки.

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/UserService.java
> +    List<UserResource> getAllUsers();
На кого му е нужно да вижда списък с всички потребители? Кой и кога би направил такава заявка?

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/impl/DoctorRatingServiceImpl.java
> +        doctorRatingEntity.setUser(userEntity);
Прегледай ми коментарите за Mapping анотацията и като цяло за mapper-ите ти.
В момента, в който направиш нужните промени такива добавки в сървис класовете ти вече няма да са ти нужни и логиката ти ще бъде една идея по-подредена.

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/java/com/example/skincarerecs/service/impl/DoctorRatingServiceImpl.java
> +        doctorRatingEntity.setUser(userEntity);
Важи за всички подобни методи в Сървис класовете ти

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/resources/application.properties
> +spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
какво прави това пропърти?

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/main/resources/application.properties
> +server.port=8080
това си е дефолтния порт по прицнип, не е нужно да го сетваш
Реакт  приложението ти върви на 3000, така че няма да имаш проблеми

2024-02-05 17:25 UTC, Teddy15 commented on backend/src/test/java/com/example/skincarerecs/BackendApplicationTests.java
> +@SpringBootTest
В някакъв момент, ще е хубаво да добавиш поне unit tests към приложението ти.
Важи и за Бекенда и за Фронтенда.

2024-02-05 17:43 UTC, Teddy15 requested changes

2024-02-05 17:43 UTC, Teddy15 commented on frontend/package-lock.json
Добави го git ignore-a на проекта този файл.

2024-02-05 17:43 UTC, Teddy15 commented on frontend/public/logo512.png
В някакъв момент изтрий тези дефолтни изображения

2024-02-05 17:43 UTC, Teddy15 commented on frontend/tailwind.config.js
> +  content: ["./src/**/*.{js,jsx,ts,tsx}",],
Планираш да пишеш и JavaScript, и TypeScript?

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/styles.css
> +/* styles.css */
Ако вече си си избрала някакви дефолтни цветове, шрифтове и тн, добави си ги в App.css, защото те са общи за целия app

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Welcome.js
> +// src/components/WelcomePage.js
Може би Welcome не е най-идеалното име за този компонент

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Navbar.js
> +// src/components/Navbar.js
Хубаво  е в папката ти components/ да имаш отделни папки за компонентите.
Тоест, Navbar компонетът ти ще се намира в components/navbar
Защо? Защото понякога е нужно компонентите да си имат специфичен css само за тях. В такъв случай, ето така биха ти изглеждали пътищата:
components/navbar/Navbar.js
components/navbar/navbar.css
Изцяло от гледна точка на подреденост и четимост е коментарът

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Products.js
> +        axios.get('http://localhost:8080/api/v1/products')
Такива ендпоийнти е добре да са изведени в отделен файл и да са константи

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Products.js
> +                                    className="mb-2 w-full h-auto" // Adjust max height as needed
Такива коментари са ненужни

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Products.js
> +                                    className="mb-2 w-full h-auto" // Adjust max height as needed
Важи  за всичките ти компоненти
За да не копирам коментара на много места го пиша

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Questionnaire.js
> +// src/components/QuestionPage.js
Компонентът ти се казва Questionaire, но експортваш QuestionPage?

2024-02-05 17:43 UTC, Teddy15 commented on frontend/src/components/Results.js
> +// src/components/ResultsPage.js
Компонентът ти се казва Results, но експортваш ResultsPage?

2024-02-05 17:45 UTC, Teddy15 requested changes

2024-02-05 17:45 UTC, Teddy15 commented on frontend/src/components/Navbar.js
> +import React from 'react';
Искам да прочетеш за js и jsx файловете как се ползват, по какво се различават и да видиш дали не е нужно да добавиш jsx файлове

2024-05-19 19:06 UTC, closed without merging